# Force HTTPS
if ($scheme ~* ^(?!https).*$) {
	return 301 https://$host$request_uri;
}

# Force www.site.com => site.com
if ($host ~* ^www\.(.+)$) {
	return 301 $scheme://$1$request_uri;
}

# Remove index.php$
if ($request_uri ~ "^/(.*)(?<=/)index\.php[/?]?((?<=[/?]).*)?$") {
	return  301 /$1$2;
}

# Remove trailing slash.
if (!-d $request_filename) {
	rewrite ^/(.+)/$ /$1 permanent;
}

# Clean Double Slashes
if ($request_uri ~* "\/\/") {
	rewrite ^/(.*) /$1 permanent;
}

# Disable access to hidden files/folders
location ~* /\.(?!well-known/) {
	deny all;
	log_not_found off;
	access_log off;
}

# Disable access to backup/config/command/log files
location ~* (?:\.(?:bak|co?nf(ig)?|in[ci]|log|sh|sql|tar|t?gz)|~)$ {
	deny all;
}


location / {
	try_files $uri /index.php?$query_string;
}

location ~ \.php$ {
	fastcgi_pass $php_server:9000;
	try_files $fastcgi_script_name =404;

	include fastcgi.conf;
}
